# Generated by Django 2.1.2 on 2019-01-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_publish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='image',
            field=models.ImageField(default=None, max_length=150, upload_to='app/media/%Y/%m/%d/', verbose_name='Archivo'),
            preserve_default=False,
        ),
    ]
