# Generated by Django 2.1.2 on 2019-01-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='value',
        ),
    ]
