# Generated by Django 2.1.2 on 2019-01-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190131_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_result',
            name='result',
            field=models.PositiveIntegerField(default='20', verbose_name='Nota entre 0 y 100, calculada con base a las respuestas enviadas'),
            preserve_default=False,
        ),
    ]
