# Generated by Django 2.1.2 on 2019-01-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190131_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_result',
            name='result',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota entre 0 y 100, calculada con base a las respuestas enviadas'),
        ),
    ]
