# Generated by Django 2.1.2 on 2019-02-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190131_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['login']},
        ),
    ]
