# Generated by Django 2.1.2 on 2019-02-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190205_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(max_length=150, unique=True, upload_to='app/media/%Y/%m/%d/', verbose_name='Archivo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
