# Generated by Django 2.1.2 on 2019-02-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titulo'),
        ),
    ]
