# Generated by Django 2.1.2 on 2019-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190208_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Titulo'),
        ),
    ]
