# Generated by Django 2.1.2 on 2021-08-12 23:17

import app.defs
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('active', models.BooleanField(default=True, help_text='Indica si el modelo está operativo', verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('indicators_link', models.URLField(blank=True, max_length=100, null=True, unique=True, verbose_name='Link')),
                ('approved', models.PositiveSmallIntegerField(default=1, help_text='> 0', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Porcentaje de aprobado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pilot_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pilot_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Piloto',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('active', models.BooleanField(default=True, help_text='Indica si el modelo está operativo', verbose_name='Activo')),
                ('avatar', models.ImageField(default='camara.jpg', upload_to=app.defs.media_upload_to)),
                ('notepad', models.TextField(blank=True, default='', null=True, verbose_name='Bloc de Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('pilot', models.ManyToManyField(to='user.Pilot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Perfile',
            },
        ),
    ]
